export enum EmailTemplates {
  RESET_PASSWORD = 'reset-password',
  REGISTER = 'registration',
  EMAIL_VERIFICATION = 'email-verification',
  INVITE_USER_TO_COMMUNITY = 'invite-community-member',
  INVITE_USER_TO_GROUP = 'invite-group-member',
  JOIN_REQUEST = 'join-request',
  INVITE_USER_TO_COMMUNITY_DYNAMIC = 'invite-community-dynamic-member',
  INVITE_USER_TO_GROUP_DYNAMIC = 'invite-group-dynamic-member',
  INVITE_CO_ORGANIZER = 'contest-co',
  INVITE_INVESTOR = 'invite-investor',
  INVESTOR = 'investor',
  WELCOME_INVESTOR = 'welcome-investor',
  COMMUNITY_CREATE = 'community-create',
  COMMUNITY_POST_COMMENT = 'community-post-comment',
  GROUP_POST_COMMENT = 'group-post-comment',
  EVENT_TIME_UPDATE = 'event-time-update',
  CONTEST_CONTESTANT_JOIN_REQUEST = 'contest-contestant-join-request',
  CONTEST_JUDGE_JOIN_REQUEST = 'contest-judge-join-request',
  CONTEST_CONTESTANT_ACCEPT = 'contest-contestant-accept',
  CONTEST_JUDGE_ACCEPT = 'contest-judge-accept',
  INVITE_EXPERT = 'invite-expert',
  PROJECT_INVESTOR_INVITE = 'project-investor-invite',
  MASTERCLASS_JOIN_REQUEST = 'masterclass-join-request',
  MASTERCLASS_INVITE_STUDENT = 'masterclass-invite-student',
  MASTERCLASS_INVITE = 'masterclass-invite',
  GENERATE_OTP = 'generate-otp',
}
