export enum YES_NO {
  YES = 'YES',
  NO = 'NO',
}

export enum TRUE_FALSE {
  TRUE = 'TRUE',
  FALSE = 'FALSE',
}

export enum PROJECT_STATUS {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
}

export enum GIG_STATUS {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PUBLISHED = 'PUBLISHED',
}

export enum GIG_ACCEPT_PAYMENT {
  BANK_TRANSFER = 'BANK_TRANSFER',
  HBB = 'HBB',
}

export enum LAUNCH_TYPE {
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  HUBBERS_ACCELERATOR = 'HUBBERS_ACCELERATOR',
}

export enum PAYMENT_METHOD {
  CREDIT_CARD = 'CREDIT_CARD',
  COMMUNITY_TOKEN = 'COMMUNITY_TOKEN',
}

export enum PAYMENT_OPTION {
  FULL_AMOUNT = 'FULL_AMOUNT',
  INSTALLMENT_PLAN = 'INSTALLMENT_PLAN',
}

export enum TRANSACTION_STATUS {
  IN_PROCESS = 'IN_PROCESS',
  DELIVERED = 'DELIVERED',
  COMPLETE = 'COMPLETE',
}

export enum TRANSACTION_TYPE {
  HBB = 'HBB',
  HBS = 'HBS',
  CURRENCY = 'CURRENCY',
}
