export enum YES_NO {
  YES = 'YES',
  NO = 'NO',
}

export enum TRUE_FALSE {
  TRUE = 'TRUE',
  FALSE = 'FALSE',
}
export enum PRICING_CURRENCY {
  CREDIT_CARD = 'CREDIT_CARD',
  HBB_TOKEN = 'HBB_TOKEN',
}

export enum PRICING_TYPE {
  ONE_TIME = 'ONE_TIME',
  INSTALLMENT = 'INSTALLMENT',
}

export enum REVIEW_FILTER {
  MOST_RECENT = 'MOST_RECENT',
  MOST_RELEVANT = 'MOST_RELEVANT',
}

export enum REPORT_TYPE {
  INAPPROPRIATE_MASTERCLASS = 'INAPPROPRIATE_MASTERCLASS',
  COPYRIGHT_VIOLATIONS = 'COPYRIGHT_VIOLATIONS',
  FAKE_INFORMATION = 'FAKE_INFORMATION',
  INAPPROPRIATE_BEHAVIOR = 'INAPPROPRIATE_BEHAVIOR',
}

export enum GIG_REPORT_TYPE {
  INAPPROPRIATE_EXPERTISE = 'INAPPROPRIATE_EXPERTISE',
  COPYRIGHT_VIOLATIONS = 'COPYRIGHT_VIOLATIONS',
  FAKE_INFORMATION = 'FAKE_INFORMATION',
  INAPPROPRIATE_BEHAVIOR = 'INAPPROPRIATE_BEHAVIOR',
}

export enum PROJECT_STATUS {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
}

export enum PROPOSAL_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
}

export enum PROPOSAL_JOB_STATUS {
  OPEN = 'OPEN',
  WORKING = 'WORKING',
  COMPLETED = 'COMPLETED',
}

export enum PROPOSAL_PAYMENT_TYPE {
  CREDIT_CARD = 'CREDIT_CARD',
  COMMUNITY_TOKEN = 'COMMUNITY_TOKEN',
}

export enum PROPOSAL_BILLING_FREQUENCY {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}

export enum PROPOSAL_RATE_TYPE {
  FIXED = 'FIXED',
  HOURLY = 'HOURLY',
}

export enum PROPOSAL_FILTER {
  LATEST = 'LATEST',
  OLDEST = 'OLDEST',
  HIGHEST = 'HIGHEST',
  LOWEST = 'LOWEST',
}

export enum FILE_UPLOAD_BY {
  CLIENT = 'CLIENT',
  FREELANCER = 'FREELANCER',
}

export enum JOB_STATUS {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum GIG_REQUEST_STATUS {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
}

export enum PROJECT_OWNER_FILTER {
  ANYONE = 'ANYONE',
  CREATED_BY_ME = 'CREATED_BY_ME',
}

export enum PROJECT_SORT {
  DATE_CREATED = 'DATE_CREATED',
  TITLE_NAME = 'TITLE_NAME',
  LAST_OPEN = 'LAST_OPEN',
}

export enum GIG_RESPONSE_STATUS {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
}

export enum GIG_REQUEST_STATE {
  NEW = 'NEW',
  ON_GOING = 'ON_GOING',
  PAST = 'PAST',
}

export enum GIG_REQUEST_RESPONSE_STATUS {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  NOT_SENT = 'NOT_SENT',
}

export enum CANVAS_MEMBER_STATUS {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
}

export enum CANVAS_MEMBER_TYPE {
  MEMBER = 'MEMBER',
  EXPERT = 'EXPERT',
}

export enum GIG_STATUS {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PUBLISHED = 'PUBLISHED',
}

export enum INVITE_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum GIG_ACCEPT_PAYMENT {
  BANK_TRANSFER = 'BANK_TRANSFER',
  HBB = 'HBB',
}

export enum LAUNCH_TYPE {
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  HUBBERS_ACCELERATOR = 'HUBBERS_ACCELERATOR',
}

export enum MARKET_FILTER {
  ALL = 'ALL',
  JUST_ADDED = 'JUST_ADDED',
  TRENDING = 'TRENDING',
  MOST_POPULAR = 'MOST_POPULAR',
  // RECENTLY_VIEWED = 'RECENTLY_VIEWED',
  SAVED_EXPERTISE = 'SAVED_EXPERTISE',
  MY_EXPERTISE = 'MY_EXPERTISE',
  BOUGHT_EXPERTISE = 'BOUGHT_EXPERTISE',
}

export enum JOB_FILTER {
  ALL = 'ALL',
  JUST_ADDED = 'JUST_ADDED',
  RECENTLY_ADDED = 'RECENTLY_ADDED',
  TRENDING = 'TRENDING',
  MOST_POPULAR = 'MOST_POPULAR',
  SAVED_JOBS = 'SAVED_JOBS',
  MY_JOBS = 'MY_JOBS',
  RELATED_JOBS = 'RELATED_JOBS',
}

export enum JOB_SORT {
  DATE = 'DATE',
}

export enum USER_EXPERTISE_REVIEW_SORT {
  MOST_RELEVANT = 'MOST_RELEVANT',
}

export enum MARKET_FILTER_SORT_BY {
  MOST_RELEVANT = 'MOST_RELEVANT',
  MOST_RECENT = 'MOST_RECENT',
}

export enum GIG_SORT_BY {
  PRICE_ASCENDING = 'PRICE_ASCENDING',
  TITLE_ASCENDING = 'TITLE_ASCENDING',
  DATE_ASCENDING = 'DATE_ASCENDING',
  PRICE_DESCENDING = 'PRICE_DESCENDING',
  TITLE_DESCENDING = 'TITLE_DESCENDING',
  DATE_DESCENDING = 'DATE_DESCENDING',
}

export enum OPEN_MARKET_FILTER {
  ALL = 'ALL',
  JUST_ADDED = 'JUST_ADDED',
  TRENDING = 'TRENDING',
  MOST_POPULAR = 'MOST_POPULAR',
  // RECENTLY_VIEWED = 'RECENTLY_VIEWED',
}
