export enum GROUP_PRIVACY {
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC',
}

export enum GROUP_TYPE {
  GLOBAL = 'GLOBAL',
  ONLY_COMMUNITY = 'ONLY_COMMUNITY',
}

export enum TOPIC_TYPE {
  GLOBAL = 'GLOBAL',
  PRIVATE = 'PRIVATE',
}

export enum COMMUNITY_REQUEST_TYPE {
  EVENT = 'EVENT',
  GROUP = 'GROUP',
  TOPIC = 'TOPIC',
}

export enum COMMUNITY_REQUEST_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum TOPIC_STATUS {
  ALL = 'ALL',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum COMMUNITY_USER_ROLE {
  COMMUNITY_LEADER = 'COMMUNITY_LEADER',
  HOST = 'HOST',
  MODERATOR = 'MODERATOR',
  MEMBER = 'MEMBER',
}

export enum INVITATION_TYPE {
  EMAIL = 'EMAIL',
  LINK = 'LINK',
}

export enum COMMUNITY_INVITE_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum GROUP_STATUS {
  ALL = 'ALL',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum GROUP_INVITE_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
  ALL = 'ALL',
}

export enum GROUP_USER_ROLE {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  MODERATOR = 'MODERATOR',
}

export enum EVENT_TYPE {
  GLOBAL = 'GLOBAL',
  COMMUNITY_EVENT = 'COMMUNITY_EVENT',
  GROUP_EVENT = 'GROUP_EVENT',
}

export enum EVENT_STATUS {
  ALL = 'ALL',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum REACTION_TYPE {
  LIKE = 'LIKE',
  DISLIKE = 'DISLIKE',
}

export enum HIDE_UNHIDE {
  HIDE = 'HIDE',
  UNHIDE = 'UNHIDE',
}

export enum FOLLOW_REACTION_TYPE {
  FOLLOW = 'FOLLOW',
  UNFOLLOW = 'UNFOLLOW',
}

export enum YES_NO {
  YES = 'YES',
  NO = 'NO',
}

export enum CONTEST_RULES {
  HUBBERS_STANDARD_RULES = 'HUBBERS_STANDARD_RULES',
  OWN_RULES = 'OWN_RULES',
}

export enum TRUE_FALSE {
  TRUE = 'TRUE',
  FALSE = 'FALSE',
}

export enum CONTEST_STATE {
  COMPLETED = 'COMPLETED',
  DRAFTED = 'DRAFTED',
  ONGOING = 'ONGOING',
  PENDING = 'PENDING',
}

export enum CLIME_PRIZE_STATUS {
  CLAIMED = 'CLAIMED',
}

export enum ATTENDEE_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum POST_TYPE {
  POST = 'POST',
  POLL = 'POLL',
  SHARE_LOCATION = 'SHARE_LOCATION',
  ARTICLE = 'ARTICLE',
  SHARED_CONTENT = 'SHARED_CONTENT',
}

export enum COMMUNITY_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
}

export enum COMMUNITY_TYPE {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
  SECRET = 'SECRET',
}

export enum SHARED_CONTENT_TYPE {
  POST = 'POST',
  ARTICLE = 'ARTICLE',
  POLL = 'POLL',
  LOCATION_SHARING = 'LOCATION_SHARING',
  EVENT = 'EVENT',
  GROUP = 'GROUP',
}

export enum POST_SHARE_TYPE {
  EVENT = 'EVENT',
  MASTER_CLASS = 'MASTER_CLASS',
  FREELANCER = 'FREELANCER',
  EXPERTISE = 'EXPERTISE',
  POST = 'POST',
}

export enum POST_LOCATION {
  COMMUNITY = 'COMMUNITY',
  GROUP = 'GROUP',
}
export enum TOPIC_LOCATION {
  COMMUNITY = 'COMMUNITY',
  GROUP = 'GROUP',
}

export enum POST_STATUS {
  PUBLISHED = 'PUBLISHED',
  REMOVE = 'REMOVE',
}

export enum POLL_STATUS {
  PUBLISHED = 'PUBLISHED',
  REMOVE = 'REMOVE',
}

export enum CONTESTANT_ROLE {
  CONTESTANT = 'CONTESTANT',
  JUDGE = 'JUDGE',
}

export enum CONTESTANT_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum CONTEST_SUBMISSION_STATUS {
  UNDER_REVIEW = 'UNDER_REVIEW',
  REVIEWED = 'REVIEWED',
}

export enum CONTEST_FILTER {
  ALL = 'ALL',
  JUST_ADDED = 'JUST_ADDED',
  TRENDING = 'TRENDING',
  MOST_POPULAR = 'MOST_POPULAR',
  CONTESTS_APPLIED = 'CONTESTS_APPLIED',
  SAVED_CONTESTS = 'SAVED_CONTESTS',
  MY_CONTESTS = 'MY_CONTESTS',
}

export enum CONTEST_FILTER_SORT {
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC',
  DATE = 'DATE',
}
