export enum ADMIN_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
}

export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum CONTESTANT_ROLE {
  CONTESTANT = 'CONTESTANT',
  JUDGE = 'JUDGE',
}

export enum TRUE_FALSE {
  TRUE = 'TRUE',
  FALSE = 'FALSE',
}

export enum CONTEST_STATE {
  COMPLETED = 'COMPLETED',
  DRAFTED = 'DRAFTED',
  ONGOING = 'ONGOING',
  PENDING = 'PENDING',
}

export enum CONTEST_RULES {
  HUBBERS_STANDARD_RULES = 'HUBBERS_STANDARD_RULES',
  OWN_RULES = 'OWN_RULES',
}

export enum PROFILE_TYPES {
  CREATOR = 'CREATOR',
  EXPERT = 'EXPERT',
  INVESTOR = 'INVESTOR',
  HUBBERS_TEAM = 'HUBBERS_TEAM',
}

export enum COMMUNITY_USER_ROLE {
  COMMUNITY_LEADER = 'COMMUNITY_LEADER',
  HOST = 'HOST',
  MODERATOR = 'MODERATOR',
  MEMBER = 'MEMBER',
}

export enum COMMUNITY_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
}

export enum EVENT_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum GROUP_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum TOPIC_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum GROUP_PRIVACY {
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC',
}

export enum GROUP_TYPE {
  GLOBAL = 'GLOBAL',
  ONLY_COMMUNITY = 'ONLY_COMMUNITY',
}

export enum LAUNCH_TYPE {
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  HUBBERS_ACCELERATOR = 'HUBBERS_ACCELERATOR',
}

export enum YES_NO {
  YES = 'YES',
  NO = 'NO',
}

export enum UPDATE_ORDER {
  PRODUCT_CATEGORY = 'PRODUCT_CATEGORY',
  PRODUCT_SUB_CATEGORY = 'PRODUCT_SUB_CATEGORY',
  PRODUCT_SUB_CATEGORY_FAQ = 'PRODUCT_SUB_CATEGORY_FAQ',
}

export enum ASSIGN_SHARE_FILTER {
  AREA = 'AREA',
  SUBAREA = 'SUBAREA',
  USER = 'USER',
}

export enum PARTNERSHIP_AREA {
  GLOBAL = 'GLOBAL',
  LOCAL = 'LOCAL',
}

export enum EVENT_TYPE {
  GLOBAL = 'GLOBAL',
  COMMUNITY_EVENT = 'COMMUNITY_EVENT',
  GROUP_EVENT = 'GROUP_EVENT',
}

export enum COMMUNITY_TYPE {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
  SECRET = 'SECRET',
}

export enum TOPIC_TYPE {
  GLOBAL = 'GLOBAL',
  PRIVATE = 'PRIVATE',
}

export enum TOPIC_LOCATION {
  COMMUNITY = 'COMMUNITY',
  GROUP = 'GROUP',
}

export enum PARTNERSHIP_DURATION {
  SIX_MONTHS = 'SIX_MONTHS',
  TWELVE_MONTHS = 'TWELVE_MONTHS',
}

export enum COMMUNITY_INVITE_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum SHARE_METHOD {
  INITIAL = 'INITIAL',
  USER = 'USER',
  CONVERSION = 'CONVERSION',
}

export enum COURSE_STATUS {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
}

export enum WORKSPACE_CATEGORY_LABEL {
  BETA = 'BETA',
  CO_CREATING = 'CO_CREATING',
}

export enum WALKTHROUGH_TYPE {
  START_TOUR = 'START_TOUR',
  TOUR_STEP = 'TOUR_STEP',
  END_TOUR = 'END_TOUR',
}

export enum WHEN_LAUNCH {
  NOW = 'NOW',
  IN_ONE_THREE_MONTHS = 'IN_ONE_THREE_MONTHS',
  AFTER_SIX_MONTHS = 'AFTER_SIX_MONTHS',
  NO_ESTIMATIVE = 'NO_ESTIMATIVE',
}

export enum TIME_AVAILABILITY {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  SPECIFIC_HOURS_A_WEEK = 'SPECIFIC_HOURS_A_WEEK',
}

export enum EXP_INVESTOR {
  ZERO_TWO = 'ZERO_TWO',
  THREE_SIX = 'THREE_SIX',
  PLUS_SEVEN = 'PLUS_SEVEN',
}

export enum EXP_TEACHER {
  ZERO_TWO = 'ZERO_TWO',
  THREE_SIX = 'THREE_SIX',
  PLUS_SEVEN = 'PLUS_SEVEN',
}
