export enum ROLES {
  CREATOR = 'CREATOR',
  EXPERT = 'EXPERT',
  INVESTOR = 'INVESTOR',
  TEACHER = 'TEACHER',
  HUBBERS_TEAM = 'HUBBERS_TEAM',
  STANDARD = 'STANDARD',
}

export enum PARTNER_TYPE {
  PRIVATE = 'PRIVATE',
  GLOBAL = 'GLOBAL',
}

export enum TRUE_FALSE {
  TRUE = 'TRUE',
  FALSE = 'FALSE',
}

export enum USER_CREATED_BY {
  SELF = 'SELF',
  ADMIN = 'ADMIN',
}

export enum CONTENT_TYPE {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
}

export enum PORTFOLIO_TYPE {
  EXPERT = 'EXPERT',
  CREATOR = 'CREATOR',
  INVESTOR = 'INVESTOR',
}

export enum YES_NO {
  YES = 'YES',
  NO = 'NO',
}

export enum PARTNERSHIP_AREA {
  GLOBAL = 'GLOBAL',
  LOCAL = 'LOCAL',
}

export enum WHEN_LAUNCH {
  NOW = 'NOW',
  IN_ONE_THREE_MONTHS = 'IN_ONE_THREE_MONTHS',
  AFTER_SIX_MONTHS = 'AFTER_SIX_MONTHS',
  NO_ESTIMATIVE = 'NO_ESTIMATIVE',
}

export enum TIME_AVAILABILITY {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  SPECIFIC_HOURS_A_WEEK = 'SPECIFIC_HOURS_A_WEEK',
}

export enum MERGE_ACCOUNT_STATUS {
  PENDING = 'PENDING',
  ON_GOING = 'ON_GOING',
  COMPLETED = 'COMPLETE',
}

export enum EXPERT_REVIEW_SORT_BY {
  MOST_RELEVANT = 'MOST_RELEVANT',
  MOST_RECENT = 'MOST_RECENT',
}

export enum EXPERT_FILTER {
  RECENTLY_JOINED = 'RECENTLY_JOINED',
  RECENTLY_VIEWED = 'RECENTLY_VIEWED',
  ALL = 'ALL',
  JUST_ADDED = 'JUST_ADDED',
  TRENDING = 'TRENDING',
  MOST_POPULAR = 'MOST_POPULAR',
  SAVED_JOBS = 'SAVED_JOBS',
  MY_JOBS = 'MY_JOBS',
  RELATED_JOBS = 'RELATED_JOBS',
}

export enum EXPERT_SORT {
  DATE = 'DATE',
}

export enum EXP_INVESTOR {
  ZERO_TWO = 'ZERO_TWO',
  THREE_SIX = 'THREE_SIX',
  PLUS_SEVEN = 'PLUS_SEVEN',
}

export enum EXP_TEACHER {
  ZERO_TWO = 'ZERO_TWO',
  THREE_SIX = 'THREE_SIX',
  PLUS_SEVEN = 'PLUS_SEVEN',
}

export enum ADMIN_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  STAFF = 'STAFF',
}

export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  CLOSED = 'CLOSED',
}

export enum USER_STATE {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}

export enum SETTING_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum PROFILE_TYPES {
  CREATOR = 'CREATOR',
  EXPERT = 'EXPERT',
  TEACHER = 'TEACHER',
  INVESTOR = 'INVESTOR',
  HUBBERS_TEAM = 'HUBBERS_TEAM',
}

export enum PARTNERSHIP_DURATION {
  SIX_MONTHS = 'SIX_MONTHS',
  TWELVE_MONTHS = 'TWELVE_MONTHS',
}
